# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Player_Pos": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://houssemeddinebayoudha.github.io/Predict_Player_Pos/"

git_url = "https://github.com/houssemeddinebayoudha/Predict_Player_Pos/tree/master/"

def custom_doc_links(name): return None
